import { NextRequest } from "next/server";
import { sendEmail } from "@/lib/email";

export async function POST(request: NextRequest) {
  try {
    const data = await request.json();
    const { name, email, phone, path, messages } = data;

    if (!name || !email || !phone || !path) {
      return Response.json(
        { error: "Missing required fields" },
        { status: 400 }
      );
    }

    const isLive = path === "live";
    const pathText = isLive ? "Live Representative" : "AI Concierge";
    const subject = `[Chatbot Lead] ${name} - Selected ${pathText}`;

    // Format chat history log if provided
    let chatHistoryHtml = "";
    let chatHistoryText = "";
    if (messages && Array.isArray(messages) && messages.length > 0) {
      chatHistoryText = "\nCHAT CONVERSATION HISTORY:\n" + messages.map((m: any) => `${m.sender.toUpperCase()}: ${m.text}`).join("\n");
      
      const messageList = messages
        .map((m: any) => {
          const isBot = m.sender === "bot";
          const bg = isBot ? "#0b2d20" : "#1a3d30";
          const name = isBot ? "AI Concierge" : "Client";
          return `
            <div style="background-color: ${bg}; padding: 10px; margin-bottom: 8px; border-radius: 4px; border: 1px solid rgba(222, 192, 126, 0.15);">
              <span style="font-weight: bold; font-size: 11px; color: #dec07e; text-transform: uppercase; display: block; margin-bottom: 4px;">${name}:</span>
              <span style="font-size: 13px; color: #ffffff;">${m.text}</span>
            </div>
          `;
        })
        .join("");

      chatHistoryHtml = `
        <h4 style="color: #dec07e; margin-top: 25px; margin-bottom: 10px; text-transform: uppercase; font-size: 12px; letter-spacing: 1px;">Conversation History:</h4>
        <div style="max-height: 300px; overflow-y: auto; padding: 10px; background-color: #020f0a; border: 1px solid #1f362b; border-radius: 4px;">
          ${messageList}
        </div>
      `;
    }

    // Admin Notification Email
    const adminText = `
New lead collected via AI Chatbot Assistant.
--------------------------------------------------
Client Name: ${name}
Email: ${email}
Phone: ${phone}
Preference: ${pathText}
${chatHistoryText}
`;

    const adminHtml = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 25px; border: 1px solid #dec07e; background-color: #051c14; color: #ffffff; border-radius: 8px;">
        <div style="text-align: center; margin-bottom: 25px; border-bottom: 1px solid #1f362b; padding-bottom: 15px;">
          <span style="font-size: 20px; font-weight: bold; color: #ffffff; letter-spacing: 2px;">FANTASTICLIMO</span><br/>
          <span style="font-size: 9px; color: #dec07e; letter-spacing: 3px; font-weight: bold; text-transform: uppercase;">AI Chatbot lead capture</span>
        </div>

        <h3 style="color: #dec07e; margin-top: 0; font-size: 16px;">New Concierge Lead Alert</h3>
        <p style="font-size: 14px; color: #ccc;">A client has interacted with the chatbot and provided their contact information.</p>

        <table style="width: 100%; border-collapse: collapse; margin: 20px 0; background-color: #08251a; border: 1px solid #1f362b; border-radius: 6px;">
          <tr>
            <td style="padding: 12px; font-weight: bold; width: 150px; border-bottom: 1px solid #1f362b; color: #dec07e;">Client Name:</td>
            <td style="padding: 12px; border-bottom: 1px solid #1f362b; color: #ffffff;">${name}</td>
          </tr>
          <tr>
            <td style="padding: 12px; font-weight: bold; border-bottom: 1px solid #1f362b; color: #dec07e;">Email Address:</td>
            <td style="padding: 12px; border-bottom: 1px solid #1f362b;"><a href="mailto:${email}" style="color: #ffffff; text-decoration: none;">${email}</a></td>
          </tr>
          <tr>
            <td style="padding: 12px; font-weight: bold; border-bottom: 1px solid #1f362b; color: #dec07e;">Phone Number:</td>
            <td style="padding: 12px; border-bottom: 1px solid #1f362b;"><a href="tel:${phone}" style="color: #ffffff; text-decoration: none;">${phone}</a></td>
          </tr>
          <tr>
            <td style="padding: 12px; font-weight: bold; color: #dec07e;">Routing Option:</td>
            <td style="padding: 12px; color: #f3e5c8; font-weight: bold; text-transform: uppercase; font-size: 12px; letter-spacing: 1px;">
              ${isLive ? "⚠️ LIVE REPRESENTATIVE NEEDED" : "🤖 CHATTING WITH AI CONCIERGE"}
            </td>
          </tr>
        </table>

        ${chatHistoryHtml}

        <p style="margin-top: 30px; font-size: 11px; color: #7f998c; text-align: center; border-top: 1px solid #1f362b; padding-top: 15px;">
          This lead notification was automatically generated by the FantasticLimo AI Chatbot System.
        </p>
      </div>
    `;

    // Dispatch email to Info@fantasticlimo.ca
    await sendEmail({
      to: process.env.CHATBOT_EMAIL,
      subject,
      text: adminText,
      html: adminHtml,
    });

    return Response.json({ success: true }, { status: 200 });
  } catch (error) {
    console.error("Failed to process chatbot lead:", error);
    return Response.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
